ath25: fix compilation with kernel 5.4
1. Kernel commit e7bfb3fdbde3 ("mtd: Stop updating erase_info->state
   and calling mtd_erase_callback()") removed erase_info->state
   updates and calls of mtd_erase_callback(). Do the same for our
   local MTD driver

2. Use phy_set_max_speed() to limit advertised speed. This is needed
   to suppress compilation errors:

   drivers/net/ethernet/atheros/ar231x/ar231x.c:1153:20: ...
     error: assignment to expression with array type
     phydev->supported &= (SUPPORTED_10baseT_Half
                       ^~

Signed-off-by: Adrian Schmutzler <freifunk@adrianschmutzler.de>